export enum Screens {
    SIGN_IN = "Sign In",
    SIGN_UP = "Sign Up",
    ACCOUNT = "Account",
    USER_PROFILE = "User Profile",
    USER_SEARCH = "Find people",
    MY_PROFILE = "My Profile",
    EDIT_PROFILE = "Edit Profile",
    USER_QUERIES = "Queries",
    USER_GROUPS = "Groups",
    USER_RELATIONS = "Relations",
    FOLLOWERS = "Followers",
    FOLLOWING = "Following",
    GUIDE_ME = "Guide Me",
    QUERY_VIEW = "QueryView",
    QUERY_CREATE = "New Query",
    RESPONSE_CREATE = "New Response",
    RIDE = "Find a ride",
    CREATE_GROUP = "Plan Ride",
    GROUP_VIEW = "View Group",
    CHATS = "Chats",
    CHAT_GROUP = "Group",
    CHAT_DIRECT = "Direct",
    USER_DIRECT_CHAT = "DIRECT CHATS",
    CHAT_GROUP_LIST = "CHAT_GROUP_LIST",
    CHAT_LIST_SCREEN = "Chats",
    PACKAGE_DELIVERY = "Package Delivery",
    GROUPS_SCREEN = "Guilds",
}
export enum Navs {
    AUTH = "Welcome",
    ROOT = "App Root",
    APP = "Travel Buff",
    PROFILE = "PROFILE",
    RIDE = "RIDE",
    PACKAGE_DELIVERY = "PACKAGE_DELIVERY",
    GUIDE_ME = "GUIDE_ME",
    CHATS = "CHATS"
}